import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

// app/layout.tsx
import { ThemeModeScript } from 'flowbite-react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Removed unused geistMono declaration

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning className={geistSans.variable}>
    <head>
        <ThemeModeScript />
    </head>
    <body>{children}</body>
</html>
  );
}

